[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    "setuptools>=61",
    "setuptools_scm[toml]>=7.0",
    "wheel",
]

[tool.setuptools_scm]

[project]
name = "pygem"
version = "0.2.5"
authors = [
  { name="David Rounce", email="drounce@cmu.edu" },
]
description = "Python Glacier Evolution Model for large-scale glacier modeling"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["license", "dependencies"]

[project.urls]
"Homepage" = "https://github.com/drounce/PyGEM"