[project]
name = "pygem"
version = "0.3.1"
description = "Python Glacier Evolution Model (PyGEM)"
readme = "README.md"
requires-python = ">=3.9,<3.13"
license = {file = "LICENSE.txt"}
authors = [
     {name = "David Rounce", email = "drounce@cmu.edu"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyyaml",
    "oggm",
    "salem",
    "tables",
    "geopandas",
    "xarray",
    "pandas",
    "numpy",
    "scipy",
    "matplotlib",
    "rasterio",
    "pyproj",
    "torch",
    "gpytorch",
    "scikit-learn",
    "tqdm",
    "jupyter"
]

[project.urls]
documentation = "https://pygem.readthedocs.io/"
repository = "https://github.com/drounce/PyGEM"

[project.scripts]
run_calibration_icethickness_consensus = "pygem.bin.run.run_calibration_icethickness_consensus:main"
run_calibration_frontalablation = "pygem.bin.run.run_calibration_frontalablation:main"
run_calibration = "pygem.bin.run.run_calibration:main"
run_simulation = "pygem.bin.run.run_simulation:main"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"